---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-aws-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-aws-loadbalancer
  template:
    metadata:
      labels:
        name: app-aws-loadbalancer
    spec:
      serviceAccountName: app-aws-loadbalancer
      containers:
        - name: app-aws-loadbalancer
          # Replace this with the built image name
          image: "REPLACE_IMAGE"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: ~/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "app-aws-loadbalancer"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_DEBUG_LOGS
              value: "True"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: runner
          emptyDir: {}
